name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
        
  build-autogptq:
    uses: localagi/ai-pipeline/.github/workflows/operation-docker-build-publish.yml@v3
    with:
      registry-repo-name: autogptq
      context-repository: PanQiWei/AutoGPTQ
      context-repository-ref: ${{ github.ref }}
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      build-args: |
        AUTOGPTQ_SUBSYSTEM=${{ matrix.subsystem }}
      flavor: |
        suffix=-${{ matrix.subsystem }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        subsystem: [ llama, triton ]
